# Generated by Django 4.1.2 on 2022-10-07 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('short_bio', models.CharField(max_length=250)),
                ('long_bio', models.TextField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='media/advocates/')),
                ('advocate_years_exp', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.URLField()),
                ('type', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('TWITTER', 'Twitter'), ('GITHUB', 'Github')], max_length=50)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advocates.advocate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
