# Generated by Django 4.1.2 on 2022-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='address',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='type',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
