# Generated by Django 4.1.2 on 2022-10-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0002_remove_socialmedia_address_remove_socialmedia_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='advocate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='advocates.advocate'),
        ),
    ]
