# Generated by Django 4.1.2 on 2022-10-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_logo_alter_company_summary'),
        ('advocates', '0003_alter_socialmedia_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advocates', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='long_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='advocates/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='advocate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='advocates.advocate'),
        ),
    ]
