# Generated by Django 4.1.2 on 2022-10-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocates', '0004_alter_advocate_company_alter_advocate_long_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
