# Generated by Django 4.1.2 on 2022-10-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
